BedrockStreaming/i18n-tools

packages/i18n-lint/package.json, packages/i18n-lint/src/index.js
- fix the package.json. Add the `i18n-lint` commande in order to run the module.
- add `#!/usr/bin/env node` in the index file.
=> fix(i18n-lint): fix missing bin

packages/react-i18n/package.json
Because we don't want a duplicate lodash dependency in our bundle 😄
=> Publish es module for tree shaking

packages/react-i18n/README.md, packages/react-i18n/src/components/__tests__/__snapshots__/i18nElement.component.spec.js.snap, packages/react-i18n/src/components/__tests__/i18nElement.component.spec.js, packages/react-i18n/src/components/i18nElement.component.js
Allow use of React element in `element` props of `HtmlTrans`.
=> feat(react-i18n): allow react element in HtmlTrans element prop

.travis.yml
Upgrade yarn version for travis build. It seem's that the 1.6.0 is not available anymore 🤔
=> test(yarn): upgrade yarn version for travis build

packages/react-i18n/src/__tests__/index.spec.js, packages/react-i18n/src/index.js
Export `tFunction` from utils, in order to use outside react context.
=> feat(react-i18n): export tFunction from utils

packages/eslint-plugin-i18n/package.json, packages/react-i18n/README.md, packages/react-i18n/src/components/i18n.provider.js, packages/react-i18n/src/utils/__tests__/i18n.utils.spec.js, packages/react-i18n/src/utils/i18n.utils.js
We need to monitor if some untranslated keys are displayed in production. For that we need the possibility to provide a callback for calling monitoring on untranslated keys
I add an `errorCallback` parameter in translate function, with `_.noop` default value so the code remains backward compatible. The callback can be given as props in the Provider.
⚠️ I also run a quick `yarn format` 😅
=> feat(react-i18n): add errorCallback for missing translations

package.json, packages/eslint-plugin-i18n/package.json, packages/i18n-lint/.babelrc, packages/i18n-lint/package.json, packages/react-i18n/package.json, yarn.lock
Needs #56 
Lerna handles parrallel task on all packages natively. No need to add a lot of _npm scripts_ for that.
- upgrading tools
- reducing size of `package.json` file
- add multiple config for `i18n-lint` to be able to have more than one output (one for babel: Node current, one for publishing: es2015)
=> chore(lerna): handle better usage of lerna

packages/eslint-plugin-i18n/package.json, yarn.lock
As we use `lerna` for the release and publish process we don't need `mversion` anymore
Bye Bye mversion
=> chore(devDependencies): remove useless package mversion

packages/i18n-lint/src/index.js, packages/i18n-lint/src/reader.js, packages/i18n-lint/src/runner.js, packages/i18n-lint/tests/test.config.json
As the translation files architecture changed, we need to update how the linter find those files.
i18n conf already exists for the eslint plugin in the .eslintrc.json file.
The "i18n-lint" command could use this file to know where translation files are located.
=> feat(i18n-lint): use .eslintrc.json as translation files path source

packages/react-i18n/README.md, packages/react-i18n/src/components/i18n.provider.js, packages/react-i18n/src/utils/__tests__/__snapshots__/i18n.utils.spec.js.snap, packages/react-i18n/src/utils/__tests__/i18n.utils.spec.js, packages/react-i18n/src/utils/html.utils.js, packages/react-i18n/src/utils/i18n.utils.js
We would like our customer to be able to add some HTML in their translation.
Parse translation and render HTML tags with react.
- classic interpolation for text and numbers is performed first
- props are supported
- JSX interpolation now use the parser
- iframe and script tags are ignored (with all their children)
By default the feature is off. You need to activate it by setting the `parseHTML` attribute to `true` in the Provider
=> feat(react-i18n): render HTML elements

packages/i18n-lint/src/verifiers/__tests__/__snapshots__/htmlVerifier.spec.js.snap, packages/i18n-lint/src/verifiers/__tests__/htmlVerifier.spec.js, packages/i18n-lint/src/verifiers/htmlVerifier.js
We need to match opening tags with attributes.
Update the regexp.
=> fix(i18n-lint): improve opening tag regexp

packages/react-i18n/src/components/i18nElement.component.js, packages/react-i18n/src/components/i18nString.component.js
Fix a bug when using <Trans /> component.
Signature for the translate function changed but its call from Trans and HtmlTrans components didn't.
=> fix(react-i18n): fix components call to t function

packages/react-i18n/types.d.ts
ReactElement type was badly used, as we use those component in JSX we need to have the type of a Function ou use FC utility
=> chore: fixup typings to remove JSX error

packages/react-i18n/README.md, packages/react-i18n/jest.setup.js, packages/react-i18n/package.json, yarn.lock
- the library react-i18n still required react 16 in peerDependencies
- it supports react 17 without issue
- so I allowed react 17 in the peerDependencies so that we have no warning when using the lib in a project with react 17, and no duplicate version of react
=> chore(react-i18n): upgrade to react 17

packages/react-i18n/package.json
When requiring the lib, webpack can't do its [tree-shaking](https://webpack.js.org/guides/tree-shaking/) properly because of the commonjs require.
The problem I face is that, I need to import the translateFunction but I can't require it because when Webpack require the whole lib Next.JS throws an error because of the createContext used elsewhere in the lib. If we enable the treeshaking, only the function that I need will be imported and Next.JS won't throw an error.
- Added the property `sideEffects: false` in the package.json of react-i18n as specified in [the webpack doc](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)
=> chore(react-i18n): disable sideEffect to allow webpack tree-shaking

.gitignore, packages/eslint-plugin-i18n/src/rules/interpolation-data.js, packages/eslint-plugin-i18n/src/rules/no-unknown-key.js, packages/i18n-lint/src/runner.js, packages/i18n-lint/src/verifiers/htmlVerifier.js, packages/i18n-lint/src/verifiers/jsonVerifier.js, packages/react-i18n/.babelrc, packages/react-i18n/package.json, packages/react-i18n/src/utils/html.utils.js, packages/react-i18n/src/utils/i18n.utils.js, yarn.lock
Remove old and deprecated configuration of webpack for lodash tree shaking.
Just import the used function from lodash to prevent it to being fully loaded in projects.
Move lodash import to package's peer dependencies to allow different version in projects.
=> chore(deps): cleanup lodash imports and add it as peer

.github/workflows/continuous-integration.yml, package.json, packages/eslint-plugin-i18n/CHANGELOG.md, packages/eslint-plugin-i18n/package.json, packages/i18n-lint/CHANGELOG.md, packages/i18n-lint/package.json, packages/react-i18n/CHANGELOG.md, packages/react-i18n/package.json, yarn.lock
Fix a bug introduced by https://github.com/BedrockStreaming/i18n-tools/pull/134 when build no longer work on project. And fix some minor versions of dependencies
=> chore(deps): update deps and fix lodash import

packages/eslint-plugin-i18n/package.json, packages/react-i18n/package.json
When using theses packages with our app. The peerDependencies resolutions makes our package manager warn us about unmet peerDependencies. 
We want to be able to use react-i18n with React 18.
We want to be able to use eslint-plugin-i18n.
We widen the peerDependencies specifier:
- We want to allow React 18 to work with react-i18n with '|| ^18.0.0'
- We want to allow any Eslint version above 4.0.0
=> chore(deps): widen the peerDependencies in the package.json's

packages/i18n-lint/src/verifiers/__tests__/__snapshots__/htmlVerifier.spec.js.snap, packages/i18n-lint/src/verifiers/__tests__/htmlVerifier.spec.js, packages/i18n-lint/src/verifiers/htmlVerifier.js
At bedrock we want to add translations with a static href value and the current linter never captures the open anchor tag.
eg: '<a href="http://www.m6.fr/html5">some link</a>' will fail because it won't have a open tag captured
Add a second capture group just for this case
=> fix: cover edge cases for anchor tags

.gitignore, packages/react-i18n/src/utils/__tests__/i18n.utils.spec.js, packages/react-i18n/src/utils/i18n.utils.js
I want to use i18n with German from Germany. As such, I need to be able to handle plurals. Basing myself on what already exists for other customers, I've added the plural for the `de` language.
- Copy/paste what was already existing for `nl`
- Add tests in the same way
=> feat(react-i18n): add possibility to make german plural
